### ISSUE TITLE
Edit Profile Permissions - Not working

### ISSUE THREAD

**Issue by idanblich** [benedwards44/fieldcreator#1]
Hi, 
I created new field with the app ,
Label : test , Name : test__c , Type: text , Options : use the default , Profiles : read + edit = true.

The new field created BUT with out the profile Profile Permissions.
I tried to disable and enable back - no change.
I tried to apply to this field  - no change.
I tried to apply to allfield  - no change.
In Addition i saw you note on the "Deploying Fields..." alert but after 24 hours the profile didn't changed.

Idan

**Comment by benedwards44** [comment]
Cheers, mate, I will have a look and let you know.

**Comment by benedwards44** [comment]
This is fixed in the latest commit, cheers.

**Comment by idanblich** [comment]
Hi , 
Thanks for the quick response .. 
Now the app create profile permissions , But create it as Visible +  Read only no mater what the the UI choice was.
I'm not python dev , but i will look into the code

**Comment by benedwards44** [comment]
Are you sure? The permissions appears to be working correctly for me. Tested as Read and Edit, Read Only and no permissions.

**Comment by idanblich** [comment]
Yep .. 
Using the https://fieldcreator.herokuapp.com and not locally, 
Chrome (Mac) Version 43.0.2357.81 (64-bit)

**Comment by vijoshp18** [comment]
It used to work before, however profile permissions are notworking for me now! 
Created few fields on sandbox and they didn't have permission.

**Comment by JasonHoult1981** [comment]
Profile Permissions are not working for me either. Using the https://fieldcreator.herokuapp.com

**Comment by benedwards44** [comment]
Sorry guys, finally got around to fixing this 😬
