### ISSUE TITLE
FIELD_INTEGRITY_EXCEPTION - Save or update not supported in active organizations.

### ISSUE THREAD

**Issue by RedaBenh** [benedwards44/fieldcreator#2]
Enable to create a single field in a production org !
I get this message: 
![image](https://cloud.githubusercontent.com/assets/1609466/21017717/92f5eae0-bd6a-11e6-9fcf-a8ac882f1ce2.png)

But in a developper org it work fine

**Comment by benedwards44** [comment]
@RedaBenh this is a limitation of the Salesforce Tooling API unfortunately, not of the app itself.

**Comment by shawnholt** [comment]
So this cannot be used in production?  Get this with a brand new object.

**Comment by benedwards44** [comment]
That is correct, the Tooling API doesn't support deploying direct to
Production Orgs.
