### ISSUE TITLE
Field_Integrity_Exception

### ISSUE THREAD

**Issue by wjtre20** [benedwards44/fieldcreator#3]
Started getting these errors for fields in the sandbox. Not sure what is the issue.
![image](https://cloud.githubusercontent.com/assets/15255251/24866866/1904e070-1dd1-11e7-8c57-2ede3229238f.png)

**Comment by benedwards44** [comment]
Hey mate, I think the issue is that you're creating long text/rich text fields with a length of 255 (needs to be 256 or higher).

I've updated the settings to default to 131,072 when doing long text and rich text fields.
