### ISSUE TITLE
Field Level Security. 

### ISSUE THREAD

**Issue by Gmarkay** [benedwards44/fieldcreator#4]
Thank you for this, saved me so much time. 

One issue is that it seems to automatically set field level security to invisible, and then I have to individually update the FLS for each field. Do you know if there is a way to change this before I do the mass create?

Thanks

**Comment by RensVerhagen** [comment]
I'm having the same issue using the field creator app to create fields in bulk, FLS for all created fields is disabled for all profiles although View and Edit permissions are checked from within the toolkit.

**Comment by benedwards44** [comment]
@Gmarkay @RensVerhagen Sorry for the delay, I've fixed this now. Turns out it was just an issue of forgetting to add the Metadata URL to the callout to deploy the profiles.

**Comment by RensVerhagen** [comment]
Thnx for the fix!
